### ISSUE TITLE
A crash in the most recent version

### ISSUE THREAD

**Issue by 0xa08ab242** [Kromtec/LegendsViewer#58] opened 2020-10-15 21:40 UTC
Hi, I got this error when trying to import my world after using dfhack export legends info (and later when retrying using export legends all)

This is the popup:
![crash_popup](https://user-images.githubusercontent.com/13651167/96187076-9e468780-0ef9-11eb-8a83-e8ba2c90b2c7.png)

Here is a copy/paste of the "exception text" (in case the image doesn't show enough):
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at LegendsViewer.Legends.Events.MasterpieceArch..ctor(List`1 properties, World world)
   at LegendsViewer.Legends.Parser.XmlParser.AddEvent(String type, List`1 properties)
   at LegendsViewer.Legends.Parser.XmlParser.AddItemToWorld(List`1 properties)
   at LegendsViewer.Legends.Parser.XmlParser.ParseSection()
   at LegendsViewer.Legends.Parser.XmlParser.Parse()
   at LegendsViewer.Legends.World..ctor(BackgroundWorker worker, String xmlFile, String historyFile, String sitesAndPopulationsFile, String mapFile, String xmlPlusFile)
   at LegendsViewer.FileLoader.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

I am also attaching the exported files...
...bumping up the against the 10MB attachment size limit, will try splitting the zip into 3 files below the limit... (with 1 per message in 2 responses/comments following this).
[legends-Eternals-00426-06-12.001.zip](https://github.com/Kromtec/LegendsViewer/files/5388036/legends-Eternals-00426-06-12.001.zip)

Thanks

**Comment by 0xa08ab242** [comment] 2020-10-15 21:41
here's the second part of the zip
[legends-Eternals-00426-06-12.002.zip](https://github.com/Kromtec/LegendsViewer/files/5388043/legends-Eternals-00426-06-12.002.zip)

**Comment by 0xa08ab242** [comment] 2020-10-15 21:42
and finally, here is the third part of the zip
[legends-Eternals-00426-06-12.003.zip](https://github.com/Kromtec/LegendsViewer/files/5388050/legends-Eternals-00426-06-12.003.zip)

Thanks again

**Comment by narolol** [comment] 2020-10-17 13:16
I'm having the same exact problem. While troubleshooting I confirmed that the issue happens while reading the 'plus' XML file. If you delete it, Legends Viewer will load up with no other issues.

Hope this helps!

**Comment by JakeTrans** [comment] 2020-10-18 09:52
Running it myself it looks like some of the items are expected to be numbers but are represented as words now.  might have been  a change in the makeup of the 'Plus' XML file.

**Comment by Kromtec** [comment] 2020-10-23 12:17
Thanks for bringing this to my attention.
As JakeTrans already suspected, the new version of DFHack has changed a property from a number to a text and that caused the crash.
I have fixed it in the development branch and will close this ticket as soon as I make a new release.

**Comment by Kromtec** [comment] 2020-10-28 20:37
fixed in v.1.20.06b Hotfix release

**Closed by Kromtec** 2020-10-28 20:37 UTC
