### ISSUE TITLE
Reddit report "There was an error loading this XML file! Do you wish to attempt a repair?"

### ISSUE THREAD

**Issue by clinodev** [Kromtec/LegendsViewer#48] opened 2020-03-09 01:18 UTC
Hey there, passing on a reddit report with a pastebin link.
https://www.reddit.com/r/dwarffortress/comments/ff6dje/preview_win64_04704_pack_caveat_emptor_edition/fjynacj/

Text:

>Lordbobsaget
 
>LegendsViewer straight up just doesn't work.

>Loading the xml file in gives a popup saying "There was an error loading this XML file! Do you wish to attempt a repair?"

>Selecting yes gives a Microsoft .NET Framework Exception

(https://pastebin.com/5eTxq3EQ)

>If you select continue the program does nothing and never loads the legends file.

**Comment by Kromtec** [comment] 2020-03-09 09:40
Thanks, I contacted the poster of the issue.
I presume, [this](http://www.bay12games.com/dwarves/mantisbt/view.php?id=11357) could be the cause of the problem. If that is the case, I cannot fix it and Toady has to format user inputs in a way that they do not corrupt the xml file.

**Comment by Kromtec** [comment] 2020-03-10 10:26
It was [this](https://github.com/DFHack/dfhack/issues/1512) DFHack script error, that should be fixed in their next version.

**Closed by Kromtec** 2020-03-10 10:26 UTC
