### ISSUE TITLE
Creature Race Names not displaying

### ISSUE THREAD

**Issue by geouk1** [Kromtec/LegendsViewer#53] opened 2020-05-09 10:45 UTC
The "races" drop down menu isn't diplaying the subfilter catagories correctly. It seems like they are all there, but their names haven't registered. Instead, for each one it simply says: "LegendsViewer.Legends.CreatureInfo"

Don't know if this is a general bug or because of my world (haven't modded or changed anything about the game). I'm playing on 0.47.04, with DFHack 0.47.04-r1.

Any idea about what's going on?

Thanks so much for your work buddy. I spend so much time on Legend's Viewer, sometimes more than the actual game I love it so much! 
![Screenshot (41)](https://user-images.githubusercontent.com/65070560/81471647-733d6680-91ea-11ea-9598-fedcb6742d73.png)

**Comment by JakeTrans** [comment] 2020-08-10 18:30
Hi,

First off to echo geouk1 Thanks for making this I started using this years ago and it open my eyes to how detailed the world is.

I think I've found the cause of the issue, I believe it is due to the race becoming a object rather than a string. I took a fork and was able to get the race to show with a few tweaks. Would it be useful if I was to resubmit a pull request with my changes?

Thanks again for all your work,

Jake

**Comment by Kromtec** [comment] 2020-08-10 19:34
Hi Jake,

of course it would be useful. Feel free to make a pull request, but please to the 'develop' branch and not directly to 'master'.
I am on vacation the next few days, so I might not be able to react quickly.

Thank you for tackling this issue!

**Comment by JakeTrans** [comment] 2020-08-10 20:23
I've raised the pull request, let me know if there any problems, it's the first time I've done this.

have a nice vacation.

Thanks,

**Comment by Kromtec** [comment] 2020-08-11 06:56
You did everything correct. 😃 
I will close the issue with the next release.

**Closed** 2020-08-23 18:47 UTC
Labels: bug
